# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for WarcraftLogs Analyzer GUI."""

from PyInstaller.utils.hooks import collect_data_files

pyside6_datas = collect_data_files("PySide6")

a = Analysis(
    ["launcher.py"],
    pathex=["packages/wcl-core/src", "packages/wcl-store/src"],
    binaries=[],
    datas=[
        ("packages/wcl-core/src/wcl_core/data", "wcl_core/data"),
        ("warcraftlogs_client/templates", "warcraftlogs_client/templates"),
        ("logo.png", "."),
        ("config.example.json", "."),
    ]
    + pyside6_datas,
    hiddenimports=[
        "warcraftlogs_client.gui",
        "warcraftlogs_client.gui.app",
        "warcraftlogs_client.gui.main_window",
        "warcraftlogs_client.gui.download_view",
        "warcraftlogs_client.gui.raids_view",
        "warcraftlogs_client.gui.raid_group_view",
        "warcraftlogs_client.gui.character_view",
        "warcraftlogs_client.gui.settings_view",
        "warcraftlogs_client.gui.compare_view",
        "warcraftlogs_client.gui.insights_view",
        "warcraftlogs_client.gui.boss_insights_view",
        "warcraftlogs_client.gui.nav_stack",
        "warcraftlogs_client.gui.raid_analysis_widget",
        "warcraftlogs_client.gui.raid_list_widget",
        "warcraftlogs_client.gui.character_history_widget",
        "warcraftlogs_client.gui.raid_cross_analysis_widget",
        "warcraftlogs_client.gui.charts",
        "warcraftlogs_client.gui.detail_panel",
        "warcraftlogs_client.gui.table_models",
        "warcraftlogs_client.gui.worker",
        "warcraftlogs_client.gui.styles",
        "warcraftlogs_client.paths",
        "warcraftlogs_client.analysis",
        "warcraftlogs_client.auth",
        "warcraftlogs_client.client",
        "warcraftlogs_client.config",
        "warcraftlogs_client.database",
        "warcraftlogs_client.spell_manager",
        "warcraftlogs_client.consumes_analysis",
        "warcraftlogs_client.cache",
        "warcraftlogs_client.dynamic_role_parser",
        "warcraftlogs_client.models",
        "warcraftlogs_client.version",
        "warcraftlogs_client.updater",
        "warcraftlogs_client.gui.update_dialog",
        "warcraftlogs_client.renderers.markdown",
        "warcraftlogs_client.renderers.console",
        "warcraftlogs_client.common.data",
        "warcraftlogs_client.common.errors",
        "wcl_core.analysis",
        "wcl_core.auth",
        "wcl_core.cache",
        "wcl_core.client",
        "wcl_core.config",
        "wcl_core.consumes_analysis",
        "wcl_core.dynamic_role_parser",
        "wcl_core.models",
        "wcl_core.paths",
        "wcl_core.spell_manager",
        "wcl_core.common.data",
        "wcl_core.common.errors",
        "wcl_store",
        "wcl_store._codec",
        "wcl_store.errors",
        "wcl_store.repository",
        "wcl_store.sqlite",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter", "matplotlib", "numpy", "scipy", "PIL",
        # wcl-store's Postgres backend is for the Toads Hub; the desktop app only uses SQLite.
        "wcl_store.postgres", "sqlalchemy", "psycopg", "alembic",
        "PySide6.Qt3DAnimation", "PySide6.Qt3DCore", "PySide6.Qt3DExtras",
        "PySide6.Qt3DInput", "PySide6.Qt3DLogic", "PySide6.Qt3DRender",
        "PySide6.QtBluetooth",
        "PySide6.QtDBus",
        "PySide6.QtDesigner",
        "PySide6.QtHttpServer",
        "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
        "PySide6.QtNfc",
        "PySide6.QtNetworkAuth",
        "PySide6.QtPdf", "PySide6.QtPdfWidgets",
        "PySide6.QtPositioning",
        "PySide6.QtQuick", "PySide6.QtQuickWidgets", "PySide6.QtQml",
        "PySide6.QtRemoteObjects",
        "PySide6.QtScxml",
        "PySide6.QtSensors",
        "PySide6.QtSerialBus", "PySide6.QtSerialPort",
        "PySide6.QtSpatialAudio",
        "PySide6.QtSql",
        "PySide6.QtStateMachine",
        "PySide6.QtSvg", "PySide6.QtSvgWidgets",
        "PySide6.QtTest",
        "PySide6.QtTextToSpeech",
        "PySide6.QtWebChannel", "PySide6.QtWebEngine",
        "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebSockets",
        "PySide6.QtXml",
        "PySide6.QtAsyncio",
        "PySide6.QtConcurrent",
        "PySide6.QtDataVisualization",
        "PySide6.QtHelp",
        "PySide6.QtNetwork",
        "PySide6.QtOpenGL", "PySide6.QtOpenGLWidgets",
        "PySide6.QtPrintSupport",
        "PySide6.QtQuick3D", "PySide6.QtQuickControls2",
        "PySide6.QtUiTools",
        "PySide6.QtVirtualKeyboard",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="WarcraftLogsAnalyzer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon="logo.ico",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="WarcraftLogsAnalyzer",
)
